version: '3.9'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
    ports:
      - 3000:3000
